### PR TITLE
Improve the readme

### PR DESCRIPTION
**Pull request by jrsconfitto**
This updates the readme with the latest information about the project and improves the description of what we've done and other important project notices.

### CODE REVIEW

**Comment by jrsconfitto** [comment]
Using the following gif for the header:

event-map-demo

**Comment by jrsconfitto** [comment]
Anyone wanna review? If not, i'll just publish it later.

(Hint: you can see the rendered readme in this PR by going to the "Files changed" tab and then finding the [View] button on the readme file.)

**Comment by kieferm** [comment]
I have reviewed the google doc a bunch and made some changes. I will assume this has the same content so I approve.

**Comment by jrsconfitto** [comment]
@kieferm yeah, i saw those and included them 👍

**Comment by FishmanD** [comment]
I'm going to do a final review and then post the blog!

**Pull request merged**
