### PR TITLE
rename symbol to Event Map

### PR DESCRIPTION
**Pull request by kieferm**

### CODE REVIEW

**Review by jrsconfitto — APPROVED** [review]
👍 

"Event Map" makes a lot of sense to me and i think it is much more clear than "treemap".

"Treemap" makes me wonder where the tree is. i know the underlying data structure is a tree, but most users won't know and (i think) won't care.

**Comment by jrsconfitto** [comment]
Looks like we'll have to rebuild existing maps once this change comes in! It appears that my test display's "old" symbols aren't recognized!

@FishmanD make sure you have your display settings copied down or know what you want to show, we may have to rebuild things a bit!

**Comment by jrsconfitto** [comment]
Unknown symbol:

image

**Comment by FishmanD** [comment]
That is fine.

**Review by jrsconfitto — CHANGES_REQUESTED** [review]
OK, this doesn't work!

PI Vision is looking for a file name with a space in it:

image

We'll need to remove the space for code-related stuff, and change associated file names as well.

**Review by FishmanD — COMMENTED** [review]
I am fine with this.

**Review by jrsconfitto — APPROVED** [review]

**Pull request merged**
